import Head from 'next/head'
import styles from 'styles/home.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ikwunze Kelvin</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/Levi Ackerman.ico' />
      </Head>
      <main className={styles.main}>Welcome</main>
    </>
  )
}
