import Head from 'next/head'

//Components

import HomeTemplate from 'components/Home/HomeTemplate'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ikwunze Kelvin</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/Levi Ackerman.ico' />
      </Head>
      <HomeTemplate />
    </>
  )
}
